package day_1_2;

public class EmployeeReport {

    public static void main(String[] args) {

        String name = "Priyanshi Bansal";
        int id = 1023;
        String department = "Software Development";
        double salary = 85000.50;
        String joiningDate = "01-Jan-2025";

        StringBuffer report = new StringBuffer();

        
        report.append("========== Employee Profile Report ==========\n");
        report.append("Employee ID   : ").append(id).append("\n");
        report.append("Name          : ").append(name).append("\n");
        report.append("Department    : ").append(department).append("\n");
        report.append("Salary        : ₹").append(salary).append("\n");
        report.append("Joining Date  : ").append(joiningDate).append("\n");
        report.append("=============================================\n");


        report.insert(0, "Report Generated by HR System\n\n");

        report.replace(report.indexOf(department), report.indexOf(department) + department.length(), "Engineering");

   
        int salaryIndex = report.indexOf("Salary");
        int salaryEnd = report.indexOf("\n", salaryIndex) + 1;
        report.delete(salaryIndex, salaryEnd);

        // Print final report
        System.out.println(report.toString());
    }
}

